### ISSUE TITLE
XtermBlazor for color

### ISSUE THREAD

**Issue by Yz274419** [BattlefieldDuck/XtermBlazor#2]
Whether the colors can be modified when the OnData method renders

**Comment by BattlefieldDuck** [comment]
you can try

**Comment by Yz274419** [comment]
I don't quite understand how to achieve it, can you tell me? thanks!

**Comment by BattlefieldDuck** [comment]
what color do you want to change? Text color or background color?

You may check the example in https://github.com/BattlefieldDuck/XtermBlazor/blob/main/XtermBlazor.Demo.Server/Pages/Index.razor#L244, it changes the background color on button clicks.

You can try the demo in https://xtermblazor.pages.dev/

**Comment by Yz274419** [comment]
I'm sorry it took so long to get back to you. I want to change the text color, just like in the Linux terminal, the color of the folder name and the color of other file names are different and so on. I wonder how XtermBlazor achieves this effect. I have currently connected XtermBlazor to the terminal, but the color of the text is different from the terminal. I appreciate your quick response.

**Comment by BattlefieldDuck** [comment]
Not sure what is the problem, with screenshots will be better, thanks.

**Comment by Yz274419** [comment]
![image](https://user-images.githubusercontent.com/88315735/161675431-8580d130-5033-4c47-a706-2e295d6fe5dd.png)
Just like that

**Comment by BattlefieldDuck** [comment]
I guess this is the Linux terminal right? so how is the xterm one?

**Comment by Yz274419** [comment]
yes，I use your XtermBlazor, which is the same color as your demo text.
![微信截图_20220405120204](https://user-images.githubusercontent.com/88315735/161676566-793b8a6f-0382-4a20-bca0-190d92feb986.png)

How to change this color to be consistent with the terminal

**Comment by BattlefieldDuck** [comment]
How do you connect the linux terminal to xterm? Linux terminal should contain color code too.

I know chinese, you can type chinese if you want.

**Comment by Yz274419** [comment]
好的，是这样的，我现在有一个服务，在XtermBlazor中有一个OnFirstRender()方法，在此方法中，我会使用该服务尝试连接到linux终端，
![image](https://user-images.githubusercontent.com/88315735/161677821-f8f0b54a-e085-4bb7-95aa-a722a8478718.png)
他可以去执行Linux命令，然后根据OnDataRec()方法将数据写入Xterm

**Comment by Yz274419** [comment]
之后，字体的颜色一直是白色，我不知道去哪里设置或者如何更改它。

**Comment by BattlefieldDuck** [comment]
I guess the problem is the `OnDataRec`'s `e.Data` doesn't contains colored code like ANSI color code https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797#color-codes

You can try `Debug.WriteLine(Encoding.UTF8.GetString(e.Data));` to check the output directly.

**Comment by Yz274419** [comment]
Okay, I get a rough idea of what you mean, thanks for your reply, you can turn it off.

**Comment by BattlefieldDuck** [comment]
Your `e.Data` should look like this because there are ANSI color codes. If the `e.Data` doesn't contain ANSI color codes, the text will be always white.

```
[?25h[?25l[m[38;2;95;255;255m[13:31:06.244] [38;2;255;255;255m[Server thread/INFO]: Starting Minecraft: Bedrock Edition server version [38;2;95;255;255mv1.18.10[m[32X[32C[38;2;95;255;255m
[13:31:06.249] [38;2;255;255;255m[Server thread/INFO]: Online mode is enabled. The server will verify that players are authenticated to Xbox Live.
[?25h[?25l[m]0;PocketMine-MP 4.2.4[?25h[?25l[38;2;95;255;255m[13:31:06.340] [38;2;255;255;255m[Server thread/INFO]: This server is running PocketMine-MP version 4.2.4
[?25h[?25l[m[38;2;95;255;255m[13:31:06.340] [38;2;255;255;255m[Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[?25h[?25l[m[38;2;95;255;255m[13:31:06.614] [38;2;255;255;255m[Server thread/INFO]: Loading resource packs...
[?25h[m[?25l[38;2;95;255;255m[13:31:06.854] [38;2;255;255;255m[Server thread/INFO]: Preparing world "world"
[?25h[m[?25l[38;2;95;255;255m[13:31:06.935] [38;2;255;255;255m[Server thread/INFO]: Minecraft network interface running on 0.0.0.0:19132
```

![image](https://user-images.githubusercontent.com/29337428/161685712-4b6321bc-2dff-4a93-b466-e9cd46518661.png)

I suggested you check if there are any settings you can set on the `Nx_Stream()` or `Loginssh()`. If it still doesn't work, you may try another third-party C# SSH library to connect your terminal.

**Comment by Yz274419** [comment]
Yes, you are right, e.data does not contain ANSI code, thank you for your reply and wish you a pleasant life
