### ISSUE TITLE
Cannot register addon

### ISSUE THREAD

**Issue by hankovich** [BattlefieldDuck/XtermBlazor#3]
I get the following error in the console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'FitAddon')
```

`index.html` file:

```html
<script src="_content/XtermBlazor/XtermBlazor.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/xterm-addon-fit@0.5.0/lib/xterm-addon-fit.min.js"></script>
<script>
    window.XtermBlazor.registerAddon("xterm-addon-fit", new window.FitAddon.FitAddon()); // <- error is thrown here
</script>
```

Are there any ideas what is configured incorrectly?

I use .NET 7 Preview 7 + Self-hosted Blazor Web Assembly.

**Comment by BattlefieldDuck** [comment]
Sorry I had no idea why it occurs. The only thing I can think of is that `xterm-addon-fit.min.js` fails to load for some reason.

You may try to confirm the `FitAddon` exists or not on the browser developer console.
![image](https://user-images.githubusercontent.com/29337428/190400645-a5870f70-2687-4162-b2ad-67374f3eb0aa.png)

If it exists it should work, but if not then let's investigate together 😀

**Comment by BattlefieldDuck** [comment]
You may also try to change
```js
window.XtermBlazor.registerAddon("xterm-addon-fit", new window.FitAddon.FitAddon());
```
to 
```js
window.XtermBlazor.registerAddon("xterm-addon-fit", new FitAddon.FitAddon());
```

**Comment by hankovich** [comment]
`xterm-addon-fit` was loaded

<img src="https://user-images.githubusercontent.com/22914850/190407033-6f8b8ae4-490c-42c1-aee6-b2ca5e1e4a84.png" width="500">

But I see the following error in the console (and do not see both `window.FitAddon` and `FitAddon`):

<img src="https://user-images.githubusercontent.com/22914850/190406867-d3eab409-7b30-4067-92c3-a92916ec2d61.png" width="500">

Here's the source of the error:

<img src="https://user-images.githubusercontent.com/22914850/190408025-610e9971-8139-4901-8967-41bf1538beea.png" width="1000">


It looks like the `xterm-addon-fit.min.js` was not applied for some reason

**Comment by hankovich** [comment]
But if I go to `https://cdn.jsdelivr.net/npm/xterm-addon-fit@0.5.0/lib/xterm-addon-fit.min.js`, copy all js, paste it to the console and execute, then `window.FitAddon` exists

![image](https://user-images.githubusercontent.com/22914850/190408904-7363e166-f602-413c-8a1c-5dc95975d447.png)

**Comment by hankovich** [comment]
Oh my, this problem somehow relates to https://github.com/serdarciplak/BlazorMonaco component.

I changed 

```
<script src="_content/BlazorMonaco/lib/monaco-editor/min/vs/loader.js"></script>
<script>require.config({ paths: { 'vs': '_content/BlazorMonaco/lib/monaco-editor/min/vs' } });</script>
<script src="_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js"></script>
<script src="_content/BlazorMonaco/jsInterop.js"></script>

<script src="_content/XtermBlazor/XtermBlazor.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/xterm-addon-fit@0.5.0/lib/xterm-addon-fit.min.js"></script>
<script>window.XtermBlazor.registerAddon("xterm-addon-fit", new window.FitAddon.FitAddon());</script>
```

to

```html
<script src="_content/XtermBlazor/XtermBlazor.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/xterm-addon-fit@0.5.0/lib/xterm-addon-fit.min.js"></script>
<script>window.XtermBlazor.registerAddon("xterm-addon-fit", new window.FitAddon.FitAddon());</script>

<script src="_content/BlazorMonaco/lib/monaco-editor/min/vs/loader.js"></script>
<script>require.config({ paths: { 'vs': '_content/BlazorMonaco/lib/monaco-editor/min/vs' } });</script>
<script src="_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js"></script>
<script src="_content/BlazorMonaco/jsInterop.js"></script>
```

i.e. reordered `script` sections for `XtermBlazor` and for `BlazorMonaco`, everythigs works like a charm now

**Comment by BattlefieldDuck** [comment]
The ordering of the `<script>` does the magic congratulation!
