### ISSUE TITLE
Ctrl+C doesn't work

### ISSUE THREAD

**Issue by hankovich** [BattlefieldDuck/XtermBlazor#4]
Hi!

Are there any chances [attachCustomKeyEventHandler](https://github.com/xtermjs/xterm.js/blob/70babeacb62fe05264d64324ca1f4436997efa1b/typings/xterm.d.ts#L538-L547) will be implemented?

As for now all `ctrl+c`s are ignored.

**Comment by BattlefieldDuck** [comment]
sure :)

**Comment by BattlefieldDuck** [comment]
Thanks for that! I also figured out that `OnKey()` also has this problem, and `v1.6.1` had fixed the issue.

I guess you may use `OnKey()` like the following code since `AttachCustomKeyEventHandler()` calls on both `key down` and `key up`.
```cs
private async Task OnKey(KeyboardEventArgs args)
{
    if (args.CtrlKey && string.Equals(args.Key, "C", StringComparison.OrdinalIgnoreCase))
    {
        string selection = await terminal.GetSelection();
        await clipboardService.CopyAsync(selection);
    }
}
```

**Comment by hankovich** [comment]
Closing as resolved. Thanks!
