### ISSUE TITLE
AttachCustomKeyEventHandlerEvaluate

### ISSUE THREAD

**Issue by Int32Overflow** [BattlefieldDuck/XtermBlazor#5]
How does the "AttachCustomKeyEventHandlerEvaluate" function work? I have tried to deactivate a certain key. However, JS errors come up.
Example:
`xterm.AttachCustomKeyEventHandlerEvaluate("(event) => event.keyCode != 38;");`

I want to disable ArrowUp and ArrowDown so that they do not move the cursor up or down.

**Comment by BattlefieldDuck** [comment]
What is the error? Can you share it thanks.
Also your C# code if possible thanks.
