### ISSUE TITLE
customKeyEventHandler is not invoked properly

### ISSUE THREAD

**Issue by Hastaroth1** [BattlefieldDuck/XtermBlazor#58]
First of all, thank you for this package.

**Describe the bug**

When using the `customKeyEventHandler` to intercept keys, the `KeyBoardEvent` object is not passed as a parameter as expected. Instead is it passed as the `this`:

![image](https://github.com/user-attachments/assets/31cf407e-438d-41d5-9c79-7f4f426d2a6b)

![image](https://github.com/user-attachments/assets/432e136e-0f72-4662-8f21-d132a8530ca8)

[I believe the issue is that `call` expects the first parameter to be the `this` context but it is called only with the `KeyboardEvent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call#syntax)

https://github.com/BattlefieldDuck/XtermBlazor/blob/main/XtermBlazor/src/index.ts#L47

![image](https://github.com/user-attachments/assets/6074f8e1-02d4-47cc-a892-aaae32c4a7c0)

I'm not sure what the `this` object is when Xtermjs calls the handler directly, but it would make sense to me to pass the terminal as the `this`.

**To Reproduce**
1. Create a terminal
2. In `OnFirstRender` or some other lifecycle method, use `terminal.SetCustomKeyEventHandler` to set a custom key handler.
3. Type anything inside the terminal
4. The function called in `SetCustomKeyEventHandler` will have no param passed and instead the `this` object will contain the event information.

**Expected behavior**

The first function param should contain the `KeyboardEvent` object.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge (WebView2)
 - Version [e.g. 22

**Comment by Hastaroth1** [comment]
I've created a pull request but I have no tested the changes.

**Comment by BattlefieldDuck** [comment]
Thanks @Hastaroth1! Great catch on the issue. I’ll review the pull request shortly.
