### ISSUE TITLE
Running  XtermBlazor on IOS 

### ISSUE THREAD

**Issue by gduchate** [BattlefieldDuck/XtermBlazor#6]
Hi
I am  trying the XtermBlazor library to run on IOS and Android. I am able to launch a basic xterm on both, the Android xterm seems to be working fine, however when running on IOS and trying to type something on the xterm I get the following error for every character I type :

2022-10-24 08:43:50.420439-0400 TestBlazorApp[14028:354017] [UIFocus] Failed to update focus with context <UIFocusUpdateContext: 0x600002764640: previouslyFocusedItem=(null), nextFocusedItem=(null), focusHeading=None>. No additional info available.

Have you seen this error before ? is there is known workaround?

Thanks

**Comment by BattlefieldDuck** [comment]
I have never seen this before. Would you mind sharing your XtermBlazor code here?

**Comment by gduchate** [comment]
Hi 
I loaded a test project on the following link. Also wanted to mentioned this error was on an IOS simulator.

https://www.dropbox.com/s/dprkyupa5p2qtot/TestBlazorApp.zip?dl=0

Thanks

**Comment by BattlefieldDuck** [comment]
I had viewed your project. You may try placing the script tags below `_framework/blazor.webview.js`
```html
<script src="_framework/blazor.webview.js" autostart="false"></script>
<script src="_content/XtermBlazor/XtermBlazor.min.js"></script>

<!-- xterm-addon-fit CDN -->
<script src="https://cdn.jsdelivr.net/npm/xterm-addon-fit@0.5.0/lib/xterm-addon-fit.min.js"></script>

<!-- Register addon to XtermBlazor -->
<script>window.XtermBlazor.registerAddon("xterm-addon-fit", new window.FitAddon.FitAddon());</script>
```

**Comment by gduchate** [comment]
Hi

I tried the recommended changes but still getting the same error on IOS.

Thanks

**Comment by BattlefieldDuck** [comment]
I would say it might be MAUI issue since MAUI is very new.

**Comment by BattlefieldDuck** [comment]
You may try to remove the `window.` like this
```razor
<script>XtermBlazor.registerAddon("xterm-addon-fit", new FitAddon.FitAddon());</script>
```
